### ISSUE TITLE
Issue with date render arrays containing #theme

### ISSUE THREAD

**Issue by vever001** [ec-europa/atomium#108]
Hello,

I noticed on EMA that the indexing fails with a fatal error: "Fatal error: Maximum function nesting level of '1024' reached, aborting!"

I dumped the problematic code here: https://gist.github.com/vever001/77e7ef6e654744fbd83fe9b77b80a37b 
Make sure you are in the atomium theme while running it. I save it to devel.php then I run it using drush: `drush php-script ../devel.php > output.txt`

Here is the output on my side: https://gist.github.com/vever001/71c782cf9b863d6bbd91e242642ea286

Can you try this and let me know if you can reproduce on your side?
At first glance it seems to come from #theme which contains an alternative theme function using double  underscores (date__form__webform_client_form_2838__date) then atomium runs into a loop.
So this may not be related to date elements only.

Thank you,
Hervé

**Comment by drupol** [comment]
Hello Hervé,

Thanks for the very precise bug report.

I will look into this asap and let you know how it goes.

Regards.

**Comment by drupol** [comment]
Hello,

I've succeeded to reproduce the issue locally.

I will need a ticket on our board to work on this, it seems it's not something that we can investigate in 5 minutes.

My main concern at this point, is why we can `render()` a textfield element and not a date element.

Is it a blocker for you right now ?

**Comment by drupol** [comment]
Could you try to update the file `atomium/atomium/templates/date/date.tpl.php` ?

From:
`<div<?php print $atomium['attributes']['wrapper']; ?>><?php print render($element); ?></div>`

To:
`<div<?php print $atomium['attributes']['wrapper']; ?>><?php print drupal_render_children($element); ?></div>`

And give us feedback ?

Thanks.

**Comment by vever001** [comment]
Hi @drupol 
It seems to work. No error anymore.
There's no actual content being rendered, except the wrapper with this particular example.
Here's what I get:
```
<div class="ecl-u-mt-m form-item form-item-submitted-date form-type-date">
</div>
```
I suppose rendering the parent was what was causing it to run into a loop?

Regards,
Hervé

**Comment by drupol** [comment]
Closing this as this is now fixed and in the development version of Atomium 7.x-2.x and 7.x-3.x
