### ISSUE TITLE
Fatal error: Argument 1 passed to atomium_block_view_alter() must be of the type array.

### ISSUE THREAD

**Issue by vever001** [ec-europa/atomium#113]
Hi @drupol 

After updating to the latest 7.x-3.x I get the following fatal:
`Recoverable fatal error: Argument 1 passed to atomium_block_view_alter() must be of the type array, null given, called in .../platform/profiles/multisite_drupal_standard/themes/atomium/atomium/includes/alter/block.inc).
`
This comes from commit https://github.com/ec-europa/atomium/commit/71fe7660a153298a6687aa4e0e941721a15fc4c3

It seems the following blocks on EMA don't pass an array to the drupal_alter:
- workbench-block => see workbench_block_view() which can `return;` early.
- Same for facetapi blocks => see facetapi_block_view() when e.g. the dependencies are not met.

I suggest to simply remove the type hinting.
NEPT ticket: https://webgate.ec.europa.eu/CITnet/jira/browse/NEPT-1975

Regards,
Hervé

**Comment by drupol** [comment]
Ho crap!

Or perhaps we could fix the workbench module?

**Comment by vever001** [comment]
Edited the description as it also applies to facetapi blocks.
It's much safer to remove the type hinting so we don't get a fatal if some module doesn't pass an array.

**Comment by drupol** [comment]
Here it is: https://www.drupal.org/node/2976812

**Comment by drupol** [comment]
Ah FacetAPI as well ?!

**Comment by drupol** [comment]
Here it is for FacetAPI: https://www.drupal.org/node/2976814

**Comment by drupol** [comment]
I pinged @pwolanin on Slack and he will push the patch on FacetAPI, for the one in Workbench module, I will see if I can contact the maintainer as well.

**Comment by vever001** [comment]
Thanks a lot @drupol 
In theory you are right all modules should return an array there.
My suggestion was to remove the type hint for retro-compatibility and compatibility with other modules that may be installed on EMA (some may still `return;` early on some conditions - haven't checked yet) or that will be installed in the future.

I'll follow your decision. If you go for leaving the type hint I'll apply the updates/patches on EMA.

**Comment by drupol** [comment]
This is the kind of issue that makes me hesitate.

1) Should we produce good code and be strict... that implies that modules who don't follow the api properly would fail (like FacetAPI or Workbench)
2) Should we bend to those inconsistencies just for the sake of it and deal with those inconsistencies ourselves ?

I'm still wondering what is the best solution... GRR

My own way to do this would be to use the best quality code everywhere and use the patches I provided.

I'll see if I have feedback from the maintainers and take actions from there.

Thanks for the bug report!

**Comment by vever001** [comment]
In this situation I'd personally go for the 2nd option because:
1. Adding the type hind is not critical (doesn't actually fix or improve anything). Although debatable I guess.
2. Implications: means the platform, all subsites also have to be updated. Also all modules on every subsite (using atomium) need to be investigated to make sure their hook_block_view() don't return null **in any condition**. Even maybe their hook_block_view_alter()?

But again, I'll follow your decision.

**Comment by drupol** [comment]
Cool I already have good feedback from @agentrickard !

https://www.drupal.org/project/workbench/issues/2976812

**Comment by agentrickard** [comment]
I would note that this is technically correct, but Drupal 7 doesn't really enforce type hinting in contrib, so it's a long uphill battle to use it.

In Drupal 8, type hinting is required.

**Comment by drupol** [comment]
Yeah ... that's true about type hinting. But this patch fixes an inconsistency between the code and what says the API... so I guess it's good to commit it.

**Comment by agentrickard** [comment]
Yeah, I committed it, but if you run into multiple examples of this error, good luck getting all of contrib updated. Easier to leave out the type hint, since it's not enforced by core.

**Comment by kameleon69** [comment]
@drupol 
What is the nexstep fotr this issue ?

**Comment by drupol** [comment]
I've removed the strict type and added a comment... https://github.com/ec-europa/atomium/blob/7.x-3.x/atomium/includes/alter/block.inc
