### ISSUE TITLE
Performance improvement on atomium_recursive_foreach()

### ISSUE THREAD

**Issue by vever001** [ec-europa/atomium#116]
Hello @drupol 

I noticed this function takes a lot of time (both exclusive and inclusive wall time).
I think it can be slightly improved by avoiding to alter the arrays just for keeping track of the recursion.
The following gives me ~37% improvement compared to the current function.
```
function atomium_recursive_foreach(array &$variables, callable $callback, $recurse = FALSE) {
  $recurse = isset($variables['#atomium_recursive']) ? $variables['#atomium_recursive'] : $recurse;

  foreach ($variables as $key => &$value) {
    if ($recurse && !empty($value) && is_array($value)) {
      atomium_recursive_foreach($value, $callback, $recurse);
    }

    call_user_func_array($callback, array($key, &$value, &$variables));
  }
}
```

Here are other functions that seem to take also a lot of resources.
Maybe we could also investigate:
- Drupal\atomium\Attributes::append
- Drupal\atomium\Attributes::__toString
- Drupal\atomium\Attributes::getStorage
- _atomium_extend_theme_hook
- _atomium_array_flatten
- atomium_process
- atomium_get_settings

Let me know,
Hervé

**Comment by drupol** [comment]
Hello Hervé,

Thanks for doing such things. There are probably room for improvements for sure.

Here are my questions:

1) I see you your function that you removed

`$variables['#atomium_recursive_processed'] = TRUE;`

Is it on purpose?

2) I also see that you change the API by adding a new parameter (_ok it's set by default to False_). Is it really needed?
I mean, the function is `atomium_recursive_foreach`, why would I need a parameter such as `$recurse` then? What's the point here?

3) Regarding functions that take a lot of resources in `Attributes class`. I tried to make it as easy as possible to use for everyone. Eg, we can use strings or arrays or arrays of arrays as input for almost all methods. All of these so-called goodies are coming with a price... and this is why you spotted it in your xhprof. Keep in mind that all of this is meant to be cached by an upfront software and this is not the top priority right now. Also, do not forget that we are no more developping the version 2. I strongly advise you to run your test with version 3.x (the one with Registry on steroids) and I invite EMA team to use it asap.

4) `_atomium_extend_theme_hook` doesn't seem to have anything special in it, are you sure you didn't set the xhprof threshold a bit too low? :-)

5) `atomium_process` is basically using atomium_recursive_foreach()... so we know.

6) `atomium_get_settings` is used 6 times in atomium. Two thirds of the calls are made in preprocesses, that in the end will be cached. The two remainings are done through hook_alter (css and field). What's the issue with it? What do you propose?

I'm a bit mitigated by this kind of request. Should we reduce make Atomium harder to use and then, faster for rendering or should we make it easy to use for everyone and a bit slower? Where's the threshold? What's the balance? Good question.

**Comment by vever001** [comment]
Hi @drupol 
The idea behind the changes I did here is to avoid altering $variables passed as reference as much as possible. Which is what cost resources.

Looking at the original code here https://github.com/ec-europa/atomium/blob/7.x-3.x/atomium/includes/common.inc#L421
It seems to me that $variables is being altered just to achieve the recursion. Which can be avoided by passing a new parameter.
$recurse is false by default in the new approach, so as in the original function "By default set the recursive to FALSE".

I tested and compared the old and new function and it achieves the same thing.
Just give it a try and let me know.

**Comment by drupol** [comment]
1) `atomium_recursive_foreach()` is only used once in `atomium_process()` which is cached anyway.

Do you really think that removing that would fix the performance issue?

2) Anyway, I still don't think that using an extra parameter is necessary at all.

Have a look at:

```php
  // By default set the recursive to FALSE.
  $variables += array(
    '#atomium_recursive' => FALSE,
  );
```

I'm already disabling by default the recurse calls by setting a variable to `TRUE` or `FALSE` in the `$variables` variable.

**Comment by vever001** [comment]
1. Could you tell me where (which layer) is caching `atomium_process()`?
2. Exactly, so if I'm not mistaken you are altering `$variables` there (also with `$variables['#atomium_recursive_processed'] = TRUE;`) just to achieve recursion no?

**Comment by drupol** [comment]
1) Drupal's default caching layer.
2) Yes, and I add a `#atomium_recursive_processed` to each child when it's processed so it doesn't go twice in it.

**Comment by drupol** [comment]
Hello,

`atomium_process()` has just been removed, see #123
