### ISSUE TITLE
Naming convention refactoring.

### ISSUE THREAD

**Issue by ademarco** [ec-europa/atomium#12]
### Scope
I propose the following refactoring which aims at:

1. Having only one php file per component with both preprocess and Atomium meta-hooks
2. Remove double underscore in meta-hooks names
3. Add `atomium` namespace in meta-hooks names
4. Standardize meta-hooks function description.

For example for the **Button** component we would have only one file called `button.component.inc` that would look like:

```php
/**
 * Implements hook_atomium_theme_HOOK().
 */
function atomium_atomium_theme_button() {
  return array(
    'button' => array(
      'render element' => 'element',
      'template' => 'button',
    ),
  );
}

/**
 * Implements hook_atomium_definition_HOOK().
 */
function atomium_atomium_definition_button() {
  return array(
    'label' => 'Button',
    'description' => 'Button template.',
    'preview' => array(
      'type' => 'submit',
      'value' => 'Save',
    ),
  );
}

/**
 * Implements hook_preprocess_HOOK().
 */
function atomium_preprocess_button(&$variables) {
  ...
}
```

### Tasks
- [x] Evaluate this
- [ ] Implement if ok

**Comment by drupol** [comment]
👍

**Comment by ademarco** [comment]
Ok I'll try to implement this, stay tuned!

**Comment by ademarco** [comment]
It now looks like this:

![image](https://cloud.githubusercontent.com/assets/153362/23557283/dcb44ade-002f-11e7-9757-1a1384d799d3.png)

I'll rename function names now.

**Comment by drupol** [comment]
👍

**Comment by ademarco** [comment]
Ok we should be done, I've also fixed comment blocks etc. we should review this carefully since I might have overlooked something! Also, we should merge this in before doing anything else since we would immediately run into conflicts if we don't do it.

**Comment by drupol** [comment]
Reopening to fix subthemes and file detection.
