### ISSUE TITLE
Why Peridot\\Leo assertions?

### ISSUE THREAD

**Issue by donquixote** [ec-europa/atomium#135]
A lot of the tests use assertions from `Period\\Leo`, instead of native PhpUnit assertions.

E.g.

        expect($actual)->to->equal($item['return']);

instead of

        self::assertSame($item['return'], $actual);

I see no benefit here.
Let's use the more common/standard/familiar solution, if there is no good reason to use something else.

**Comment by donquixote** [comment]
One difference is in the diff output on failure, but I actually prefer the native diff output from PhpUnit.

**Comment by drupol** [comment]
I don't mind changing at all.

**Comment by donquixote** [comment]
I am curious about the motivation.

**Comment by drupol** [comment]
A colleague introduced us this in PHPUnit and it was really nice, so we used it.

I absolutely for removing it and use PHPUnit exclusively.
