### ISSUE TITLE
2.x : Custom theme entries .component.inc files are not parsed

### ISSUE THREAD

**Issue by julien-** [ec-europa/atomium#173]
Using Atomium in version 2.x with the contrib module [rate](https://www.drupal.org/project/rate) (in version 7.x-1.7) the definition of hooks in a file "<my_theme>/templates/<non_default_drupal_object>.component.inc" only works the first time after a cleaned cache.

It is not the first time we have this problem after defining a custom theme entry, so I open this issue.

**Comment by julien-** [comment]
For sample, using rate module the file /<my_theme>/templates/rate/rate.component.inc is only parsed once after a cache cleared.

**Comment by drupol** [comment]
Hi,

This is because you have to create a specific directory in the `templates` directory instead of creating the `.component.inc` file in `templates`.
Have a look at the atomium_bartik subtheme to see how it's done.
