### ISSUE TITLE
Travis tests don't start for pull requests on 7.x-2.x?

### ISSUE THREAD

**Issue by donquixote** [ec-europa/atomium#178]
See e.g.
https://github.com/ec-europa/atomium/pull/177

We see this:

> At least 2 approving reviews are required by reviewers with write access.
￼Hide all checks
> 1 expected check
> continuous-integration/travis-ci Expected — Waiting for status to be reported

None of this shows a link to Travis.

@drupol Any idea why?

**Comment by drupol** [comment]
We are now using Docker and Drone, this issue can be closed.
