### ISSUE TITLE
Should we merge 7.x-2.x into 7.x-3.x?

### ISSUE THREAD

**Issue by donquixote** [ec-europa/atomium#180]
Currently, 7.x-2.x has two commits that are not merged into 7.x-3.x

- 929c2218 Update html_tag component
- 235d9271 Fix Travis configuration with PHP 5.6.

The "Update html_tag component" creates a merge conflict with 7.x-3.x.

We have some upcoming changes for the optimization that we will want to have in 7.x-2.x AND 7.x-3.x.

## Option 1: Don't merge, separate PRs. (most common)

Keep 7.x-2.x and 7.x-3.x divergent.

Future PRs can be created on one of the branches, and then cherry-picked to the other as a new PR.

## Option 2: Merge, resolve conflicts, shared PRs.

Merge 7.x-2.x into 7.x-3.x and resolve the conflict. Perhaps even without changing the code of 7.x-3.x.

Future pull requests:
- Create the PR based on 7.x-2.x, if intended for both branches.
- Merge into 7.x-2.x.
- Then merge 7.x-2.x into 7.x-3.x.

I don't know if anyone ever does this.

## Option 3: Don't merge, shared PR on common ancestor.

Keep 7.x-2.x and 7.x-3.x divergent.

Start PRs on the common ancestor commit, 888d4be9d4962a3e36a4a6e88cb9d7db4707fccb.
Merge them into each branch separately.

This would work at first, but would get difficult after some time, if the shared commit gets further and further behind.

**Comment by drupol** [comment]
Nope, the two branches are too different to be merged again together.
