### ISSUE TITLE
Backdrop: Incompatible test themes show up

### ISSUE THREAD

**Issue by laryn** [ec-europa/atomium#372]
I'm just testing Atomium again and when I first install it and go to the Appearance page to activate it, I see a few test themes that are incompatible. They should probably be removed:

![Screen Shot 2019-05-10 at 3 04 13 PM](https://user-images.githubusercontent.com/871421/57553743-12f4ba00-7335-11e9-982b-9e016428b4da.jpg)

**Comment by drupol** [comment]
These themes are themes from the tests. I'll see if I can make them disapear from UI.

**Comment by laryn** [comment]
I think there is a `hidden` flag that can be used in the `.info` but I don't recall the syntax off-hand.

**Comment by laryn** [comment]
`hidden = TRUE`

**Comment by drupol** [comment]
Fixed, thanks !
