### ISSUE TITLE
Backdrop: Hero block images aren't working

### ISSUE THREAD

**Issue by laryn** [ec-europa/atomium#374]
Kicking some tires and using Atomium or Atomium Basis, the core Hero Block images don't display:

**Atomium:**
![Screen Shot 2019-05-10 at 3 23 10 PM](https://user-images.githubusercontent.com/871421/57554622-8a2b4d80-7337-11e9-96dd-e99d2c859684.jpg)

**Atomium Basis:**
![Screen Shot 2019-05-10 at 3 22 32 PM](https://user-images.githubusercontent.com/871421/57554586-741d8d00-7337-11e9-86bf-1d82cef88053.jpg)

**Core Basis:**
![Screen Shot 2019-05-10 at 3 21 10 PM](https://user-images.githubusercontent.com/871421/57554510-459fb200-7337-11e9-87f0-07012665e8cc.jpg)

**Comment by drupol** [comment]
Going to see if I can replicate the issue and going to fix it asap.

**Comment by drupol** [comment]
Fixed in https://github.com/ec-europa/atomium/commit/e34615cc2a4a868be7e1a059e1a08d70d66a8316
