### ISSUE TITLE
Fix Views required exposed filters label

### ISSUE THREAD

**Issue by julien-** [ec-europa/atomium#431]
In a view, when an exposed filters is required we have trouble with its label : 
![image](https://user-images.githubusercontent.com/7086610/58967966-7a2b5000-87b5-11e9-8646-17d68faddb29.png)

- The label and the required marker are not displayed in the same html tag DIV
- `theme('form_required_marker__form_element_label__form_element')` is called twice

Here is my markup of my screenshot:
[issue_views_atomium_2_27.txt](https://github.com/ec-europa/atomium/files/3257839/issue_views_atomium_2_27.txt)

**Comment by drupol** [comment]
Hi Julien,

I'm not able to reproduce the issue locally.

![Screenshot_2019-06-05 content Site name](https://user-images.githubusercontent.com/252042/58971485-dabd8b80-87bb-11e9-8032-2c439ae1e6cd.png)

**Comment by julien-** [comment]
As seen in meeting, there is a missing check in /templates/form_element/form_element.component.inc:41 in "// Build the label render array manually." section
`if($element['#title_display'] !== 'invisible')`

**Comment by drupol** [comment]
Hi @julien- ,

Thanks for the meeting, it helped us finding the culprit.
The PR has been submitted for review: https://github.com/ec-europa/atomium/pull/438

Don't hesitate to give it a try and leave your approval or not, so we can merge it asap.

**Comment by drupol** [comment]
Fixed.
