### ISSUE TITLE
Use $conf variables defined in settings.php or settings.local.php.

### ISSUE THREAD

**Issue by julien-** [ec-europa/atomium#457]
When your are developer and you build your website with a production dump, you have to enable "Theme Debug" settings in the back-office (so to login in back-office) even if you had defined

```
$conf['theme_debug'] = TRUE;
$conf['allow_css_double_underscores'] = TRUE;
```
in your settings.local.php or you settings.php

**Comment by drupol** [comment]
Fixed, thanks !

**Comment by drupol** [comment]
Tag released Atomium 7.x-2.31.
