### ISSUE TITLE
Block titles first letter is cropped off

### ISSUE THREAD

**Issue by laryn** [ec-europa/atomium#80]
The block title seems to have the first letter chopped off for some reason:

Foundation:
![screen shot 2018-01-26 at 11 21 35 am](https://user-images.githubusercontent.com/871421/35452128-2c9058c8-028b-11e8-94fb-44e33357ef01.jpg)

Basis:
![screen shot 2018-01-26 at 11 21 51 am](https://user-images.githubusercontent.com/871421/35452134-3141c2f8-028b-11e8-81d9-3ebc84d2e44a.jpg)

**Comment by drupol** [comment]
Hello @laryn,

Did you tried on another instance ? With the latest development branch ?

**Comment by laryn** [comment]
@drupol Sorry, not yet. Hopefully this week though.

**Comment by laryn** [comment]
@drupol Sorry to report I see the same thing on a webserver that is not my local!

This is right after installing Backdrop 1.9 and git cloning the `backdrop` branch of atomium:
![screen shot 2018-02-06 at 10 19 12 am](https://user-images.githubusercontent.com/871421/35870462-55d7c38e-0b27-11e8-8e56-7039f6f327c8.jpg)

In case it helps:

- PHP 7.0.27
- PHP Extensions Enabled: date, dom, filter, gd, hash, json, pcre, pdo, session, SimpleXML, SPL, xml 
- MySQL, MariaDB, or equivalent version 5.5.59-cll

**Comment by laryn** [comment]
Not seeing this anymore on the latest.
