### ISSUE TITLE
Theme configuration doesn't save

### ISSUE THREAD

**Issue by laryn** [ec-europa/atomium#81]
Changing settings on the theme settings page and clicking save does not actually seem to save the information, even though the message says it was saved.

**Comment by drupol** [comment]
Hello,

I'm aware of the configuration handling, it needs to be refactored properly.

**Comment by laryn** [comment]
@drupol I don't see any settings on the theme settings page at this point -- is that intentional?

![Screen Shot 2019-05-10 at 3 15 22 PM](https://user-images.githubusercontent.com/871421/57554212-7501ef00-7336-11e9-971c-819df73c9f00.jpg)

**Comment by drupol** [comment]
Hi @laryn,

There is no theme settings in Atomium for Backdrop (for now).
Atomium is intended to be a base theme, and thus, there is no need for now to have settings.

Atomium for Drupal include some settings, but in Backdrop they are provided by the **devel** module.
