### ISSUE TITLE
Backdrop: Front page trying to render nav/tabs?

### ISSUE THREAD

**Issue by laryn** [ec-europa/atomium#82]
![screen shot 2018-01-26 at 11 47 27 am](https://user-images.githubusercontent.com/871421/35453213-fd389a00-028e-11e8-8117-9bb9f7de41ec.jpg)

I don't see these "Array" outputs in Atomium Basis but do on the others.

**Comment by drupol** [comment]
This is because the template "boxton" is not yet converted into Atomium.
Most of the variables that are passed to a templates are arrays, render arrays actually. This is why it's important to wrap the variable with render() in the .tpl.php

**Comment by laryn** [comment]
This is using the Boxton layout, but the Atomium theme. Do we need special layouts for Atomium, too?

**Comment by drupol** [comment]
"action links" and "tabs" variables are generated in [layout_preprocess_layouts()](https://github.com/backdrop/backdrop/blob/88d243bd46d2eba52195da1fa0da1a385abf7c08/core/modules/layout/layout.theme.inc#L241) and are HTML. (see for [menu_local_actions()](https://github.com/backdrop/backdrop/blob/a6d84d8a492d09e89428032cd9923dc6612ed3df/core/includes/menu.inc#L2355))

Atomium doesn't "deal" with HTML but with render arrays, everywhere.

So, in Atomium those variables are render arrays. This is why we need to use `render($action_links);` in layout-boxton.tpl.php.

**Comment by drupol** [comment]
It will be fixed in the next commit on that branch, I've added the layout and modified it accordingly.

**Comment by drupol** [comment]
Fixed in https://github.com/ec-europa/atomium/commit/fb444ca2a37602072ce361a4c5b89801e31f67ec
