### ISSUE TITLE
Custom theme registry alteration are not kept by the Atomium mechanisms

### ISSUE THREAD

**Issue by drupol** [ec-europa/atomium#96]
Modules who implements [hook_theme_registry_alter()](https://api.drupal.org/api/drupal/modules!system!system.api.php/function/hook_theme_registry_alter/7.x) to add and/or remove preprocess/process callbacks.
As the Atomium registry mechanism is rewriting those callbacks based on a function name detection, some of these callbacks are lost.
This is the case with the [views_fieldsets module](https://www.drupal.org/project/views_fieldsets).

In order to keep these alteration, I propose to re-apply the [hook_theme_registry_alter()](https://api.drupal.org/api/drupal/modules!system!system.api.php/function/hook_theme_registry_alter/7.x) after Atomium has applied its changes.

**Comment by drupol** [comment]
This issue is NEPT-1886

**Comment by voidtek** [comment]
It's merged in 7.x-2.x
